// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnfqwhplvmmstfwtbtae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxuZnF3aHBsdm1tc3Rmd3RidGFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTQ2ODEsImV4cCI6MjA2NjQzMDY4MX0.3lKxacr9wBQ3hSZzDEwA7IEjwCAlyhtQwdvzbjDebTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);